upstream:
  default:
    - 1.1.1.1
    - 1.0.0.1
blocking:
  blackLists:
    ads:
      - https://adaway.org/hosts.txt
      - https://raw.githubusercontent.com/StevenBlack/hosts/master/hosts
      - https://raw.githubusercontent.com/Perflyst/PiHoleBlocklist/master/android-tracking.txt
      - https://raw.githubusercontent.com/Perflyst/PiHoleBlocklist/master/SmartTV.txt
      - https://raw.githubusercontent.com/ftpmorph/ftprivacy/master/blocklists/xiaomi-ads-tracking.txt
      - https://raw.githubusercontent.com/AdguardTeam/FiltersRegistry/master/filters/filter_15_DnsFilter/filter.txt
      - https://raw.githubusercontent.com/jerryn70/GoodbyeAds/master/Hosts/GoodbyeAds.txt
      - https://raw.githubusercontent.com/anudeepND/blacklist/master/adservers.txt
      - https://v.firebog.net/hosts/Easyprivacy.txt
      - https://raw.githubusercontent.com/shreyasminocha/shady-hosts/main/hosts
      - https://v.firebog.net/hosts/static/w3kbl.txt
      - https://raw.githubusercontent.com/crazy-max/WindowsSpyBlocker/master/data/hosts/spy.txt
      - https://raw.githubusercontent.com/austinheap/sophos-xg-block-lists/master/easyprivacy.txt
      - https://raw.githubusercontent.com/austinheap/sophos-xg-block-lists/master/malware-domain-list.txt
      - https://raw.githubusercontent.com/kboghdady/youTube_ads_4_pi-hole/master/youtubelist.txt
  whiteLists:
    ads:
      - https://dns.bastiaandehart.com/hostfiles/whitelist.txt
  clientGroupsBlock:
    default:
      - ads
  refreshPeriod: 4h
  downloadTimeout: 2m
  downloadAttempts: 5
  downloadCooldown: 10s
caching:
  minTime: 1h
  maxTime: 24h
  prefetching: true
  prefetchExpires: 4h
prometheus:
  enable: true
port: 53
httpPort: 4000
logLevel: info