services:
  gatus:
    image: twinproduction/gatus:latest
    container_name: gatus
    restart: unless-stopped
    ports:
      - 8080:8080
    volumes:
      - ./config:/config
      - ./data:/data/