version: "3.8"
services:

  radarr:
    image: linuxserver/radarr:latest
    container_name: media-radarr
    restart: unless-stopped
    network_mode: "service:gluetun"
    depends_on:
      - gluetun
    # ports:
    #  - 7878:7878
    volumes:
      - ./radarr:/config
      - /Volumes/Media:/srv
    environment:
      - PUID=0
      - PGID=0
      - TZ=${TIMEZONE}

  sonarr:
    image: linuxserver/sonarr:latest
    container_name: media-sonarr
    restart: unless-stopped
    network_mode: "service:gluetun"
    depends_on:
      - gluetun
    # ports:
    #  - 8989:8989
    volumes:
      - ./sonarr:/config
      - /Volumes/Media:/srv
    environment:
      - PUID=0
      - PGID=0
      - TZ=${TIMEZONE}

  bazarr:
    image: linuxserver/bazarr:latest
    container_name: media-bazarr
    restart: unless-stopped
    network_mode: "service:gluetun"
    depends_on:
      - gluetun
    # ports:
    #  - 6767:6767
    volumes:
      - ./bazarr:/config
      - /Volumes/Media:/srv
    environment:
      - PUID=0
      - PGID=0
      - TZ=${TIMEZONE}

  flaresolverr:
    image: flaresolverr/flaresolverr:latest
    container_name: media-flaresolverr
    network_mode: "service:gluetun"
    depends_on:
      - gluetun
    environment:
      - TZ=${TIMEZONE}
      - CAPTCHA_SOLVER=none
    # ports:
    #  - 8191:8191
    restart: unless-stopped

  prowlarr:
    image: linuxserver/prowlarr:latest
    container_name: media-prowlarr
    restart: unless-stopped
    network_mode: "service:gluetun"
    depends_on:
      - gluetun
    environment:
      - PUID=0
      - PGID=0
      - TZ=${TIMEZONE}
    volumes:
    - ./prowlarr:/config
    # ports:
    # - 9696:9696

  ## Username: admin
  ## Password: adminadmin
  qbittorrent:
    image: linuxserver/qbittorrent:latest
    container_name: media-qbittorrent
    restart: "unless-stopped"
    network_mode: "service:gluetun"
    depends_on:
      - gluetun
    # ports:
    #  - 5080:5080 # torrent
    #  - 6881:6881 # torrent
    environment:
      - PUID=0
      - PGID=0
      - TZ=${TIMEZONE}
      - WEBUI_PORT=5080
    volumes:
      - ./qbittorrent:/config
      - /Volumes/Media:/srv

  gluetun:
    image: qmcgaw/gluetun:latest
    container_name: media-gluetun-vpn
    # container_name: gluetun
    # line above must be uncommented to allow external containers to connect.
    # See https://github.com/qdm12/gluetun-wiki/blob/main/setup/connect-a-container-to-gluetun.md#external-container-to-gluetun
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun:/dev/net/tun
    ports:
      - 8888:8888/tcp # HTTP proxy
      - 8388:8388/tcp # Shadowsocks
      - 8388:8388/udp # Shadowsocks
      - 5080:5080 # torrent
      - 6881:6881 # torrent
      - 7878:7878 # radarr
      - 8989:8989 # sonarr
      - 6767:6767 # bazarr
      #- 5055:5055 # overseerr
      - 8191:8191 # flaresolverr
      - 9696:9696 # prowlarr
      #- 5070:80 # cleanarr
    volumes:
      - ./gluetun:/gluetun
    environment:
      - VPN_SERVICE_PROVIDER=${VPN_SERVICE_PROVIDER}
      - VPN_TYPE=${VPN_TYPE}
      - OPENVPN_USER=${OPENVPN_USER}
      - OPENVPN_PASSWORD=${OPENVPN_PASSWORD}
      - SERVER_COUNTRIES=${SERVER_COUNTRIES}
      - TZ=${TIMEZONE}