services:
  postgres:
    image: postgres:latest
    container_name: teamcity-database
    restart: unless-stopped
    environment:
      - POSTGRES_PASSWORD=${PASSWORD}
      - POSTGRES_USER=${USER}
      - POSTGRES_DB=${DB}
      - PG_DATA=/var/lib/postgresql/data
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    ports:
      - 5433:5432

  teamcity:
    image: jetbrains/teamcity-server:latest
    container_name: teamcity-server
    restart: unless-stopped
    ports:
      - "8112:8111"
    volumes:
      - ./data:/data/teamcity_server/datadir
      - ./logs:/opt/teamcity/logs
    depends_on:
      - postgres