services:
  minio:
    image: docker.io/bitnami/minio:latest
    ports:
      - 9000:9000
      - 9001:9001
    networks:
      - minionetwork
    volumes:
      - ./data:/bitnami/minio/data
    environment:
      - MINIO_ROOT_USER=${USER}
      - MINIO_ROOT_PASSWORD=${PASS}
      - MINIO_DEFAULT_BUCKETS=main

networks:
  minionetwork:
    driver: bridge

volumes:
  minio_data:
    driver: local